import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import ToasterContext from './context/ToasterContext'
import AuthContext from './context/AuthContext'
import { ColorModeScript } from '@chakra-ui/react'
import theme from '../app/theme'
import ActiveStatus from './components/ActiveSatus'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Providers>
            <ColorModeScript initialColorMode={theme.config.initialColorMode} />
            <ToasterContext />
            <ActiveStatus />
            {children}
          </Providers>
        </AuthContext>
      </body>
    </html>
  )
}
